In [3]:
import numpy as np

In [13]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
print(type(a))
print(a.shape)
print (type(b))
print(b.shape)
print (a[0],b[1,1])

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
1 5


In [17]:
a = np.zeros((3,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [19]:
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
c = np.full((5,5),7)
print(c)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [29]:
d = np.eye(10)
print (d)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [31]:
e = np.random.random((2,2))

print(e)

[[0.32607588 0.5213962 ]
 [0.53068396 0.82520355]]


In [37]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

b= a[0:2,1:3]
print(b)

print(a[0,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2


In [40]:
b[1,1]=77
print(a)

[[ 1 77 77  4]
 [ 5  6 77  8]
 [ 9 10 11 12]]


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
row1 = a[1, :]
row2 = a[1:2,:]